export interface Language {
  dependencies?: string[]
  aliases?: string[]
}

export const languages: Record<string, Language> = {
  "1c": {},
  abnf: {},
  accesslog: {},
  actionscript: {},
  ada: {},
  angelscript: {},
  apache: {},
  applescript: {},
  arcade: {},
  arduino: { dependencies: ["cpp"] },
  armasm: { aliases: ["arm"] },
  asciidoc: { aliases: ["adoc"] },
  aspectj: {},
  autohotkey: { aliases: ["ahk"] },
  autoit: {},
  avrasm: {},
  awk: {},
  axapta: {},
  bash: { aliases: ["sh", "zsh"] },
  basic: {},
  bnf: {},
  brainfuck: { aliases: ["bf"] },
  cal: {},
  capnproto: { aliases: ["capnp"] },
  ceylon: {},
  clean: { aliases: ["dcl", "icl"] },
  clojure: { aliases: ["clj"] },
  "clojure-repl": {},
  cmake: { aliases: ["cmake.in"] },
  coffeescript: { aliases: ["coffee", "cson", "iced"] },
  coq: {},
  cos: { aliases: ["cls"] },
  cpp: {
    aliases: ["c", "c++", "cc", "cxx", "h", "h++", "hh", "hpp", "hxx"],
  },
  crmsh: { aliases: ["crm", "pcmk"] },
  crystal: { aliases: ["cr"] },
  cs: { aliases: ["c#", "csharp"] },
  csp: {},
  css: {},
  d: {},
  dart: {},
  delphi: {
    aliases: [
      "dfm",
      "dpr",
      "freepascal",
      "lazarus",
      "lfm",
      "lpr",
      "pas",
      "pascal",
    ],
  },
  diff: { aliases: ["patch"] },
  django: { aliases: ["jinja"] },
  dns: { aliases: ["bind", "zone"] },
  dockerfile: { aliases: ["docker"] },
  dos: { aliases: ["bat", "cmd"] },
  dsconfig: {},
  dts: {},
  dust: { aliases: ["dst"] },
  ebnf: {},
  elixir: {},
  elm: {},
  erb: {},
  erlang: { aliases: ["erl"] },
  "erlang-repl": {},
  excel: { aliases: ["xls", "xlsx"] },
  fix: {},
  flix: {},
  fortran: { aliases: ["f90", "f95"] },
  fsharp: { aliases: ["fs"] },
  gams: { aliases: ["gms"] },
  gauss: { aliases: ["gss"] },
  gcode: { aliases: ["nc"] },
  gherkin: { aliases: ["feature"] },
  glsl: {},
  gml: {},
  go: { aliases: ["golang"] },
  golo: {},
  gradle: {},
  groovy: {},
  haml: {},
  handlebars: { aliases: ["hbs", "html.handlebars", "html.hbs"] },
  haskell: { aliases: ["hs"] },
  haxe: { aliases: ["hx"] },
  hsp: {},
  htmlbars: {},
  http: { aliases: ["https"] },
  hy: { aliases: ["hylang"] },
  inform7: { aliases: ["i7"] },
  ini: { aliases: ["toml"] },
  irpf90: {},
  isbl: {},
  java: { aliases: ["jsp"] },
  javascript: { aliases: ["js", "jsx"] },
  "jboss-cli": { aliases: ["wildfly-cli"] },
  json: {},
  julia: {},
  "julia-repl": {},
  kotlin: { aliases: ["kt"] },
  lasso: { aliases: ["lassoscript", "ls"] },
  ldif: {},
  leaf: {},
  less: {},
  lisp: {},
  livecodeserver: {},
  livescript: { aliases: ["ls"] },
  llvm: {},
  lsl: {},
  lua: {},
  makefile: { aliases: ["mak", "mk"] },
  markdown: { aliases: ["md", "mkd", "mkdown"] },
  mathematica: { aliases: ["mma"] },
  matlab: {},
  maxima: {},
  mel: {},
  mercury: { aliases: ["m", "moo"] },
  mipsasm: { aliases: ["mips"] },
  mizar: {},
  mojolicious: {},
  monkey: {},
  moonscript: { aliases: ["moon"] },
  n1ql: {},
  nginx: { aliases: ["nginxconf"] },
  nimrod: { aliases: ["nim"] },
  nix: { aliases: ["nixos"] },
  nsis: {},
  objectivec: { aliases: ["mm", "obj-c", "objc"] },
  ocaml: { aliases: ["ml"] },
  openscad: { aliases: ["scad"] },
  oxygene: {},
  parser3: {},
  perl: { aliases: ["pl", "pm"] },
  pf: { aliases: ["pf.conf"] },
  pgsql: { aliases: ["postgres", "postgresql"] },
  php: { aliases: ["php3", "php4", "php5", "php6", "php7"] },
  plaintext: {},
  pony: {},
  powershell: { aliases: ["ps"] },
  processing: {},
  profile: {},
  prolog: {},
  properties: {},
  protobuf: {},
  puppet: { aliases: ["pp"] },
  purebasic: { aliases: ["pb", "pbi"] },
  python: { aliases: ["gyp", "ipython", "py"] },
  q: { aliases: ["k", "kdb"] },
  qml: { aliases: ["qt"] },
  r: {},
  reasonml: { aliases: ["re"] },
  rib: {},
  roboconf: { aliases: ["graph", "instances"] },
  routeros: { aliases: ["mikrotik"] },
  rsl: {},
  ruby: { aliases: ["gemspec", "irb", "podspec", "rb", "thor"] },
  ruleslanguage: {},
  rust: { aliases: ["rs"] },
  sas: {},
  scala: {},
  scheme: {},
  scilab: { aliases: ["sci"] },
  scss: {},
  shell: { aliases: ["console"] },
  smali: {},
  smalltalk: { aliases: ["st"] },
  sml: { aliases: ["ml"] },
  sqf: { dependencies: ["cpp"] },
  sql: {},
  stan: {},
  stata: { aliases: ["ado", "do"] },
  step21: { aliases: ["p21", "step", "stp"] },
  stylus: { aliases: ["styl"] },
  subunit: {},
  swift: {},
  taggerscript: {},
  tap: {},
  tcl: { aliases: ["tk"] },
  tex: {},
  thrift: {},
  tp: {},
  twig: { aliases: ["craftcms"] },
  typescript: { aliases: ["ts"] },
  vala: {},
  vbnet: { aliases: ["vb"] },
  vbscript: { aliases: ["vbs"] },
  "vbscript-html": {},
  verilog: { aliases: ["sv", "svh", "v"] },
  vhdl: {},
  vim: {},
  x86asm: {},
  xl: { aliases: ["tao"] },
  xml: {
    aliases: ["atom", "html", "plist", "rss", "xhtml", "xjb", "xsd", "xsl"],
  },
  xquery: { aliases: ["xpath", "xq"] },
  yaml: { aliases: ["yml"] },
  zephir: { aliases: ["zep"] },
}
